""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" General
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

set nocompatible
" let backspace acts normally
set backspace=indent,eol,start
" auto read when a file is changed from the outside
set autoread
" a buffer becomes hidden when it is abandoned
set hidden
" disable beep on errors
set noerrorbells
" flash the screen instead of beeping on errors
set visualbell
set t_vb=
" enable mouse for scrolling and resizing
set mouse=a
" encoding
set encoding=utf-8
set fileencodings=ucs-bom,utf-8,gb18030,default,latin1
set fileformats=unix,dos
" disable backup and swap
set nobackup
set nowritebackup
set noswapfile
" don't use Ex mode, use Q for formatting.
nnoremap Q gq
" don't redraw while executing macros (good performance config)
set lazyredraw
" map leader key to space
let mapleader = "\<Space>"

" open new split window to right
set splitright
" open new split window to below
set splitbelow


""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Indentation
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

" smart auto indentation (instead of old smartindent option)
filetype plugin on
filetype indent on
" no wrap lines
set nowrap
" avoid wrapping a line in the middle of a word
set linebreak
" new lines inherit the indentation of previous lines
set autoindent
" use spaces instead of tabs
set expandtab

" indent by spaces when hitting tab
set softtabstop=3
" show existing tab with spaces width
set tabstop=3
" when indenting with ‘>’, use spaces width
set shiftwidth=3

" force using tab indentation for caddy server config file
autocmd BufRead,BufNewFile [Cc]addyfile set filetype=caddyfile
autocmd FileType caddyfile setlocal noexpandtab

" disable automatically insert comment leader
autocmd FileType * setlocal formatoptions-=ro

"autocmd FileType json setlocal ts=2 sts=2 sw=2
"autocmd FileType lua setlocal ts=2 sts=2 sw=2
"autocmd FileType toml setlocal ts=2 sts=2 sw=2
"autocmd FileType yaml setlocal ts=2 sts=2 sw=2


""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Keybindings
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

" tab management
map <leader>tn :tabnew<cr>
map <leader>tc :tabclose<cr>
map <leader>to :tabonly<cr>
" tab switch
map <A-[> :tabprevious<cr>
map <A-]> :tabnext<cr>
map <A-1> :tabnext 1<cr>
map <A-2> :tabnext 2<cr>
map <A-3> :tabnext 3<cr>
" tab move
map <A-S-[> :silent! tabmove -1<cr>
map <A-S-]> :silent! tabmove +1<cr>

" opens a new tab with the current buffer's path
" super useful when editing files in the same directory
map <leader>te :tabedit <C-r>=escape(expand("%:p:h"), " ")<cr>/

" buffer switch
map <C-h> :bprevious<cr>
map <C-l> :bnext<cr>
" cope item switch (quickfix list)
map <C-j> :cnext<cr>
map <C-k> :cprevious<cr>

" save file
map <leader>w :w!<cr>
" change working directory to current buffer
map <leader>cd :cd %:p:h<cr>:pwd<cr>
map <leader>cc :ccl<cr>

" close current buffer
map <A-q> :bd<cr>
" vim(command): user defined commands must start with an uppercase letter
command BuffOnly silent! execute "%bd|e#|bd#"
map <leader>bo :BuffOnly<cr>

" split window management
map <A-c> :close<cr>
map <A-v> :vsplit<cr>
map <A-b> :split<cr>
" focus on split window on direction
map <A-h> <C-W>h
map <A-l> <C-W>l
map <A-j> <C-W>j
map <A-k> <C-W>k
" move split window to direction
map <A-S-h> <C-W>H
map <A-S-l> <C-W>L
map <A-S-j> <C-W>J
map <A-S-k> <C-W>K

" clipboard copy paste
map <leader>y "+y
map <leader>p "+p
map <leader>P "+P
" extended copy registers (which would not overwrote by 'yy', 'dd', etc)
map <leader>uy "uy
map <leader>up "up
map <leader>uP "uP
map <leader>iy "iy
map <leader>ip "ip
map <leader>iP "iP
map <leader>oy "oy
map <leader>op "op
map <leader>oP "oP

" emacs keybindings for command-line
" start of line
:cnoremap <C-a> <Home>
" back one character
:cnoremap <C-b> <Left>
" delete character under cursor
:cnoremap <C-d> <Del>
" end of line
:cnoremap <C-e> <End>
" forward one character
:cnoremap <C-f> <Right>
" recall newer command-line
:cnoremap <C-n> <Down>
" recall previous (older) command-line
:cnoremap <C-p> <Up>
" back one word
:cnoremap <Esc><C-b> <S-Left>
" forward one word
:cnoremap <Esc><C-f> <S-Right>

" clear search highlight
nmap <silent> <leader><cr> :nohlsearch<cr>


""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Search
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

" find the next match as we type the search
set incsearch
" highlight searches by default
set hlsearch
" ignore case when searching ...
set ignorecase
" ... unless you type a capital.
set smartcase

" display command line’s tab complete options as a menu
set wildmenu
" add current working dir and it's subdirs to PATH
set path+=**
" ignore compiled files
set wildignore=*.o,*~,*.pyc,*.class
if has("win32")
    set wildignore+=.git\*,.hg\*,.svn\*
    set wildignore+=node_modules\*,vendor\*
    set wildignore+=public\*
else
    set wildignore+=*/.git/*,*/.hg/*,*/.svn/*,*/.DS_Store
    set wildignore+=*/node_modules/*,*/vendor/*
    set wildignore+=*/public/*
endif


""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Cursor
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

" always show cursor position
set ruler
" highlight cursor line and column
set cursorline
set cursorcolumn
" highlight limit column
set colorcolumn=81

" reletive line number
set number


""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Netrw
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

" disable .netrwhist file
let g:netrw_dirhistmax=0
" autoclose netrw buffer
let g:netrw_fastbrowse = 0


""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Appearence
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

" always show the status line
set laststatus=2
" g Ctrl-g
set statusline=\ %F%m%r%h%w%=[%p%%\/%L]\ [%{&encoding}\/%{&fileformat}]\ %y\ 
" set the window’s title, reflecting the file currently being edited
set title

" the number of screen lines to keep around the cursor
set scrolloff=7
set sidescrolloff=5

" fonts
if has("win32")
    set gfn=JetBrains\ Mono\ NL:h12
    set gfw=Sarasa\ Mono\ SC:h14
elseif has("linux")
    set gfn=JetBrains\ Mono\ NL\ 12
endif

" disable markdown folding
let vim_markdown_folding_disabled = 1

" enable syntax highlighting
syntax on


""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Colorscheme
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

" to list built-in color themes, type `:colo <Tab>`

set background=dark
try
    colorscheme habamax
catch
    syntax off
endtry

""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Enable Plugins
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

"let s:vim_runtime = fnamemodify(resolve(expand('<sfile>:p')), ':h')
"execute 'set runtimepath+=' . s:vim_runtime
"execute 'source ' . s:vim_runtime . '/vimrc'
"call pathogen#infect(s:vim_runtime.'/plugins_vim/{}')

